### ISSUE TITLE
Add timestamp to test result

### ISSUE THREAD

**Issue by ascheibal** [corona-warn-app/cwa-quick-test-frontend#135]
## Current Implementation

Test representation as hash and test result are send from frontend to backend when the test result is confirmed. Upon registration there is a timestamp send to the mobile client that currently determines the time of test. As testees sometimes don't adhere to the schedule this timestamp may be unreliable.

## Suggested Enhancement

Pass a timestamp from the Quicktest frontend to backend when the test result is confirmed. This timestamp can be considered as confirmation time of the test. The patient record shall get and additional attribute timestamp, which is the time of generating the QRCode (timestamp value in QRCode) at test registration and will be updated with the time of confirmation at the time the test result is given.
### Interface
The existing REST payload shall be enhanced by a key `"sc": number` containing the time of confirmation in UNIX epoch format.

## Expected Benefits

As Antigen Tests give prove for certain activities (shop visits etc) and are valid for a given period of time, the exact time of the proof is crucial.

**Comment by mschulte-tsi** [comment]
This is Implemented in the Backend Only
