### ISSUE TITLE
Wording DS (dringend) 

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-frontend#155]
Datenschutz - Einwilligung: 
IST: „die DS-Hinweise…. wurden erteilt“. 
SOLL: Das muss heißen „wurden ausgehändigt“.

![grafik](https://user-images.githubusercontent.com/65922025/119476048-fb3ad380-bd4d-11eb-875b-7a1616ba17e3.png)

**Comment by vaubaehn** [comment]
@BrittaTSI @ggrund-tsi 
Dass die Datenschutzhinweise ausgehändigt wurden, wird ja durch die Auswahl der Optionsbuttons oben eigentlich schon bestätigt.
Müsste es vor der Checkbox (opt-in) also nicht eigentlich heißen:
"**Das Einverständnis** zur Verarbeitung der Daten des Antigentests durch die Testeinrichtung **wurde** erteilt." ?

**Comment by BrittaTSI** [comment]
Ja, genau, das sind zwei paar Schuhe.
1. **Die Verarbeitung der eigentlichen Testdaten durch die Teststelle.** Patient:in gibt personenbezogene Daten an und läßt sich testen. Teststelle ermittelt das Testergebnis, informiert den Patienten darüber, im Fall eines positiven Tests auch das Gesundheitsamt. Welche Daten hier erhoben und wie sie verarbeitet werden, ist gesetzlich geregelt. Hierfür müssen dem Patienten nur entsprechende Datenschutzhinweise ausgehändigt werden. Seine Einwilligung in die Testung ist dann implizit die Einverständnis in die Datenverarbeitung und wird nicht separat abgefragt /  dokumentiert. Ist er mit der DV nicht einverstanden, kann er sich nicht testen lassen und der Vorgang wird abgebrochen. 
2. **Die zusätzliche Verarbeitung einer Teilmenge der Daten in der CWA.** Hier hat der Patient die freie Wahl, ob er sich dafür oder dagegen entscheidet. Auch hier erhält er Datenschutzhinweise, die ausschließlich die DV in der CWA betreffen. Er muß in die Verarbeitung explizit einwilligen und dies muß separat dokumentiert werden.

**Comment by vaubaehn** [comment]
@BrittaTSI 
Vielen Dank für die ausführliche Antwort. Ui, ich hab's befürchtet.
Dann ist natürlich
"Die Datenschutzhinweise zur Verarbeitung der Daten des Antigentests durch die Testeinrichtung wurden ausgehändigt"
vor der Checkbox richtig.

Evtl. könnten dann jeweils die letzten Sätze zu den Optionsbuttons präzisiert werden?
"Dem Getesteten wurden **die zugehörigen** Hinweise zum Datenschutz ausgehändigt."
Vielleicht kann das vor allem den "Frischlingen" unter dem Testpersonal als Gedächtnisstütze dienen, und es noch etwas deutlicher machen, dass es also zwei unterschiedliche Blätter (von wahrscheinlich drei möglichen) herausgeben muss...?
Ist schon alles nicht einfach...
Vielen Dank für Ihren Einsatz, und weiter gutes Gelingen!

**Comment by BrittaTSI** [comment]
Unseren internen Datenschutzexpert:innen und den beratenden Juristen ging es hier insbesondere um die Einhaltung der gesetzlichen Anforderungen, die es für die Information der Patient:innen und die Dokumentation ihrer Einwilligungen geht. Da sind die Juristen ja naturgegeben sehr präzise und haben uns das Wording im Detail vorgegeben, so daß wir hier nicht ohne Rücksprache Formulierungen ändern können. 
Aber sie haben natürlich recht mit Ihrem Hinweis. Entscheidend ist auf jeden Fall, daß das Personal in den Teststellen im Vorfeld der Nutzung gut geschult ist, weiß, was zu tun ist und was die unterschiedlichen Optionen für die Patient:innen bedeuten. Die Texte, die im Frontend des Schnelltestportals angezeigt werden, werden die Tester:innen ja nicht jedesmal im Detail durchlesen.
