### ISSUE TITLE
vCard Parser mittels 2D-Imager-Scanner

### ISSUE THREAD

**Issue by NTeschner** [corona-warn-app/cwa-quick-test-frontend#159]
## Current Implementation

Man benötigt eine Webcam zum einlesen.

## Suggested Enhancement

Statt einer Webcam wäre das einlesen mittels 2D-Imager-Scanner schön.

## Expected Benefits

Privatsphäre, Geschwindigkeit und Präzision eines 2D-Imager-Scanner ist besser, als bei einer Webcam.

**Comment by topix1000** [comment]
Das wäre optimal! Bitte um zeitnahe Umsetzung. Danke!

**Comment by ggrund-tsi** [comment]
Hi @NTeschner 
um die WebApp auf möglichst vielen verschiedenen Gerätetypen laufen zu lassen, haben wir uns für die WebCam Variante entschieden. Evtl. gibt es ja eine Möglichkeit den 2D Scanner wie eine WebCam vom System ansprechen zu lassen?

Gruß, Gordon
