### ISSUE TITLE
Vergabe von eigenen Probennummern

### ISSUE THREAD

**Issue by NTeschner** [corona-warn-app/cwa-quick-test-frontend#161]
## Current Implementation

Probennummern werden vom System vorgegeben.

## Suggested Enhancement

Es gibt mittlerweile diverse Tests, die mittels Barcode eine Probennumer auf dem Testkit/Auswerter gedruckt haben. Man könnte auch diese nutzen und mittels Scanner einlesen.

## Expected Benefits

Geringerer Zeitaufwand, da das Beschriften oder Drucken von Proben-IDs entfällt.
Ökologischer und ökonomischer Gedanke.

**Comment by ggrund-tsi** [comment]
Hi @NTeschner 
dieser Ansatz ist systembedingt aktuell leider nicht umsetzbar.
Die Proben-ID wird in mehreren Systemen genutzt.

Gruß, Gordon
