### ISSUE TITLE
add DCC Consent

### ISSUE THREAD

**Issue by ggrund-tsi** [corona-warn-app/cwa-quick-test-frontend#163]

**Comment by BrittaTSI** [comment]
Im Zuge dessen Überarbeitung der kompletten Auswahlmöglichkeiten (Checkbox / Radiobutton) für CWA-Nutzung:
Ergänzung der Möglichkeit DCC-konformes Testergebnis im DCC-konformen Format
Im Zuge dessen Überarbeitung der kompletten Abfrage. Es müssen folgende Möglichkeiten angeboten werden:
-    keine Verarbeitung in der CWA
-     CWA anonym
-     CWA mit Vorname Name, Geburtsdatum
-     CWA DCC-Format
Also related to: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/136

**Comment by BrittaTSI** [comment]
Habe bei Dirk Lissfeld (Datenschutz) angefragt, ob es schon Vorarbeiten zu Wording, Entscheidungsbaum,... gibt.
Sobald Rückmeldung kommt, hänge ich die Informationen hier rein.

**Comment by BrittaTSI** [comment]
Aktualisierte Anforderung: Wir haben nach wie vor drei Möglichkeiten:
- Keine Verarbeitung in der CWA, Patient erhält Testergebnis als PDF, Aktualisierung auf DCC-konformes Format
-> Anpassung der DS-Hinweise, die der Testperson ausgehändigt werden, durch DS / Martin Schick notwendig (Britta/Jens stimmen mit Dirk Lissfeld und Martin Schick ab)
-> keine Änderung der Applikatin
- Anzeige in der CWA ohne Namen
-> keine Änderung der Applikation
- Anzeige in der CWA mit DCC-Daten (Statt nur VN, NN, BD. 
-> Aktualisierung des Beschreibungstexts (Britta/Jens stimmen mit Dirk Lissfeld und Martin Schick ab)
-> Austausch des Texts in der Applikation (Gordon)

**Comment by BrittaTSI** [comment]
@ggrund-tsi - ist noch nicht Done, da wir das Wording von DS noch nicht bekommen haben und dann noch anpassen müssen

**Comment by BrittaTSI** [comment]
Gerade nochmal beim Rechtsanwalt nachgehakt wegen der Texte. Antwort pending...

**Comment by BrittaTSI** [comment]
@a-trzewik Aktualisiertes Wording für die dccConsent Checkbox bei der Dateneingabe:
"Der Patient wünscht ein offizielles COVID-Testzertifikat der EU (DCC)."

**Comment by BrittaTSI** [comment]
@ascheibal - Hier steht das Wording.
