### ISSUE TITLE
Anzeige der Proben-Id hervorheben

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-frontend#170]
Hintergrund: 
Auf den Screens zur Datenerfassung (https://6155b8d7d3c6.schnelltestportal.de/c19quicktest/record und https://6155b8d7d3c6.schnelltestportal.de/c19quicktest/record/show) wird die Proben-ID angezeigt, die auf dem Test notiert werden und bei Erfassung des Ergebnisses eingegeben werden muß.
Hat der Tester vergessen, die ID zu notieren, kann er später die Probe nicht beschriften und das Ergebnis des Tests nicht eingeben. 
Auf den beiden Screens sollte die Proben-ID stärker hervorgehoben werden, z.B. in roter Schrift, damit der Tester nicht vergißt, sie zu notieren. 
Alternativ:  
Auf der Startseite eine Liste der letzten vergebenen Proben-ID aber nur zu erzeugten Tests (die verworfenen Proben-ID nicht einschließen)
 o Das wäre aus meiner Sicht ein leichter Weg eine nicht aufgeschriebene Proben-ID zu finden, falls der Dialog „Test anlegen“ schon geschlossen wurde

**Comment by kerstin-oppermann-tsi** [comment]
Die Proben ID kann inzwischen aus der Liste ausgewählt werden ohne dass man sie vorher kopiert haben muss.
