### ISSUE TITLE
QR Code Scan führt zu Fehlermeldung

### ISSUE THREAD

**Issue by dideldei** [corona-warn-app/cwa-quick-test-frontend#178]
## Describe the bug

Beim Versuch, den QR Code über den Test in die CWA zu scannen erscheint (bei iOS) stets eine Fehlermeldung "Code ist ungültig".

## Expected behaviour

QR Codes sollten zuverlässig eingelesen werden.

## Steps to reproduce the issue

Lege einen Test über das Webportal an, scanne auf "record/show" den QR-Code. Es erfolgt ein Stop, weil man nur wiederholen oder abbrechen kann.

https://user-images.githubusercontent.com/2151058/120542795-d13b7e00-c3eb-11eb-8c9e-e5b071443c00.mp4

## Technical details

Schnelltestportal, iOS-Version der CWA.

## Additional context

Problem kann an verschiedenen Stelle entstanden sein: Proben-IDs tatsächlich doppelt erzeugt? QR Code falsch generiert? QR Code falsch gelesen? Einlesen führt zu falscher Fehlermeldung?

**Comment by Ein-Tim** [comment]
@dideldei Did you build the quick test portal yourself (like described [here](https://github.com/corona-warn-app/cwa-quick-test-frontend#build)) or do you have access to a productive instance? 
@dsarkar FYI

**Comment by dideldei** [comment]
Productive instance. Yesterday it was all error 500. Today I get "Request failed with status code 400" when clicking "Continue" after that QC Code.

**Comment by dsarkar** [comment]
@dideldei Danke fuer den Report. Ist das Problem behoben, oder müssen wir hier weiter nachforschen?

**Comment by ddecsei** [comment]
Dear @dideldei ,

May I ask the name of the realm / partner that you are using?
We would like to check the portal settings as well.

Thanks,
David

**Comment by dideldei** [comment]
Dear @ddecsei,
the realm ist "hausarztpraxisschulzundlodders".
The QR codes are new and unscanned, I could not try it with an Android device as I try to use the portal while treating and seeing patients and I it is hard to explain it to patients why it does not work, but needs them to enter their personal details.

**Comment by kerstin-oppermann-tsi** [comment]
@dideldei the issue still happened?

**Comment by dideldei** [comment]
Haven't needed it for a while, but last time I checked, it was alright.
