### ISSUE TITLE
Error 500 when submitting the test result

### ISSUE THREAD

**Issue by redtares** [corona-warn-app/cwa-quick-test-frontend#186]
## Describe the bug

After filling out all the information and checking the boxes needed, I always get an error 500 code when submitting the result of the test to the cwa. Everything else works. I tried this on 2 different Windows 10 Devices in 2 browsers each. Nothing changed, same problem there.

## Expected behaviour

Please fix this, because we can not use the cwa quick test software at the moment to test other citizens.

## Steps to reproduce the issue

Scan QR-Code of the person to test & copy the sample-ID. Click on the button to record the test result. Fill everything out (sample-ID that was copied before) and finish the process by clicking on the button in the bottom right that says something like "submit data". After clicking on this button we always get an error 500 code. The data was not submitted correctly because the CWA of the patient says that the test result wasn't submitted yet.

## Technical details

Desktop, Win 10 (Firefox and Chrome)
Laptop, Win 10 (Firefox and Chrome)

## Additional context

![946e57cba68a73a6376fe795df63b115](https://user-images.githubusercontent.com/75011943/121334337-dc296d80-c919-11eb-9db3-41fbc9035ae2.png)

**Comment by redtares** [comment]
Realm: teststationamnok
Doesn't work on Android either.

**Comment by ggrund-tsi** [comment]
Hi @redtares,
please retest. Does it work?
Regards, Gordon

**Comment by HerrFabs** [comment]
Das selbe Problem tritt bei uns zurzeit auch auf.
Wir haben zwei Tests die wir nicht wegschicken können.
Unterschiedliche Benutzer wurden dazu ebenfalls ausporbiert.

Die Patientendaten wurden jeweils vom selben Benuzter erfasst.

Lösungsvorschläge der Hotline:
- Benutzer aus der Gruppe entfernen und wieder neu hinzufügen
- Benutzer löschen und neu anlegen
- Name der Teststelle ändern (Umlaute entfernen)
- Name der Teststelle im Demo-Portal entfernen

Die Lösungsvorschläge haben keine Verbesserung gebracht.

**Comment by kerstin-oppermann-tsi** [comment]
@HerrFabs auf welcher Umgebung tritt der Fehler auf?

**Comment by HerrFabs** [comment]
In der Live Version
Windows 10/Chrome & Firefox
