### ISSUE TITLE
Gender mandatory?

### ISSUE THREAD

**Issue by flo-so** [corona-warn-app/cwa-quick-test-frontend#190]
Why Is gender mandatory in the quickest portal?
Due to the DSGVO only necessary data may be interrogated, and the Gesundheitsamt does not ask for it.

**Comment by flo-so** [comment]
There also seem to be a problem reading it from QR-Code
GENDER:M f.ex is not interpreted

**Comment by flo-so** [comment]
And in the profile created in the CWA app (android), gender isn't included.

**Comment by ggrund-tsi** [comment]
Hi @flo-so 
Gender is required for medical archive process.
regards, Gordon
