### ISSUE TITLE
Parallele Verarbeitung von Tests mit und ohne DCC

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-frontend#192]
Update nach Input von Jens Mühlner und Heinz-Jörg Müller, 6.7.

**Ausgangssituation:**
- Im Schnelltestportal wird momentan nur eine Version des Ergebnisdokuments erstellt, aktuell ein PDF mit Daten zu Patient und Test ohne DCC-Komponente (aka Testbeleg). In Zukunft soll das Portal die Möglichkeit bieten, (auch) gedruckte DCC-Zertifikate zu erzeugen.
**Herausforderung:**
- Die Listen der Testmaterialien, die vom BfArM für den deutschen Schnelltest und von der EU als Grundlage des DCC zugelassen sind, unterscheiden sich erheblich. Wir müssen verhindern, daß ein DCC für einen Test erzeugt wird, bei dem kein EU-konformes Test-Kit verwendet wurde. Wir müssen wahrscheinlich auch sicherstellen, daß die Teststellen sich dafür entscheiden können, (nur oder auch) einfache Testbelege zu erstellen und dafür andere Test-Kits verwenden.

**Lösungsansatz:**
- Die Teststelle wird von T-Systems darüber informiert, daß als Grundlage für ein DCC spezielle Test-Kits notwendig sind und wo die aktuelle Liste zu finden ist. (Und kann dann ggf. entscheiden, ob sie überhaupt DCC-konforme Zertifikate anbieten will oder nur einfache Testbelege.)
**Offener Punkt** - Dieser Punkt muß in den Verträgen entsprechend angepaßt werden. -> Heinz-Jörg Müller / Labor-WS
**Testablauf:**
1. Der Patient muß vom Tester vor der Probenentnahme gefragt werden, ob er ein DCC wünscht oder ihm ein einfacher Testbeleg ausreicht. (Außerdem erfolgt wie gehabt die Auswahl zur Übertragung des Ergebnisses in die CWA.) 
2. Die Auswahl wird im Portal dokumentiert (z.B. über zusätzliche Checkbox bei der Eingabe der Patientendaten) und triggert den nachfolgenden Prozeß.
**Offener Punkt (Britta klärt):** Wording der Abfrage. Brauchen wir nochmal eine Abstimmung mit Datenschutz oder können wir mit den vorhandenen Texten arbeiten?
3. Nur wenn DCC in 1. ausgewählt, muß in der Eingabemaske das Feld Standardisierter Name befüllt werden (händisch oder automatisiert)
@ggrund-tsi - kriegen wir mit vertretbarem Aufwand hin, daß die Felder ein-/ausgeblendet werden in Abhängigkeit von der Checkbox? Wenn nicht, als Fallback eine Markierung "Nur für DCC notwendig".
4. Wenn DCC gewünscht, muß der Tester ein konformes Test-Kit verwenden, ansonsten genügt eines von der BfArM-Liste Die Probenentnahme erfolgt mit einem passenden Test-Kit.
5. Sobald das Ergebnis vorliegt, gibt der Tester es im Portal ein, zusammen mit den Angaben über das verwendete Testmaterial 
**Offener Punkt:** Müssen wir systemseitig sicherstellen, daß der Tester hier nur Test-Kits auswählen kann, die EU-konform sind oder können wir uns darauf verlassen, daß die Teststelle sich bei der Durchführung des Tests korrekt verhält und das tatsächlich verwendete Kit wahrheitsgemäß auswählt. (An diesem Punkt des Prozesses ist das Kind ohnehin schon insofern in den Brunnen gefallen, als der Test schon durchgeführt wurde. War das Kit nicht konform, müßte der Test wiederholt werden.) 
**Antwort Heinz-Jörg Müller: Ja.**
**-> Wenn in Schritt 2 DCC ausgewählt wurde, wird dem Tester in der Ergebniseingabemaske nur noch die Liste der EU-konformen Test-Kits angeboten.**
6. Je nach der Auswahl des Patienten wird ein Testzertifikat mit oder ohne DCC gedruckt und ihm ausgehändigt.

**Comment by ggrund-tsi** [comment]
Hi @BrittaTSI,

bis 5. passt es soweit.
Wir wissen zum Zeitpunkt der Erhebung des Testresults nicht, ob das DCC Flag ausgewählt wurde. (Mehrstufiger Prozess und unterschiedliche, eintragende Personen)
Ohne Aufbrechen des aktuellen Flows, kann man das nicht wie gefordert umsetzen. (Aufbrechen = Zeitaufwendig, weil Frontend-, Backend- und API-Anpassung und Neuentwicklung)
Gehst du da mit Heinz-Jörg Müller nochmal in die Bütt oder sollen wir es wie gefordert versuchen umzusetzen?
Bis 5. kann ich es schon mal vorbereiten.

Vielen Dank und Gruß, Gordon

**Comment by BrittaTSI** [comment]
Hi @ggrund-tsi - danke für Dein Feedback! :-)
Kurze Rückfrage noch - wo/wie würden wir denn das DCC Flag speichern? Können wir nicht nach Eingabe der Proben-ID im Ergebniseingabescreen irgendwo nachschauen, ob das Flag bei der Dateneingabe gesetzt worden ist? Wenn nicht, erschließt sich mir gerade nicht, welche Funktion das Flag hat (außer, den Tester daran zu erinnern, daß er das richtige Material verwendet)... Wir müssen das Flag doch auch später als Trigger verwenden um das DCC anzufordern, oder?

**Comment by ggrund-tsi** [comment]
Das Flag wird im Backend gespeichert, nachdem alle Daten eingegeben, der QR-Code angezeigt und der Request übermittelt wurde.
Counter und Tester arbeiten asyncron voneinander, mit wahrscheinlich unterschiedlichen Gräten.

- Daher bliebe nur das Abfragen vom Backend, ob Dcc für eine bestimmte Proben-ID enabled wurde.
- --> API und BE Anpassung/Neuentwicklung

- Momentan ist es so, dass alle Daten bei der Eingabe des Testresults gleichzeitig eingegeben werden und keine Abhängigkeiten zum BE bestehen.
- --> Testresulteingabe müsste mehrstufig gestaltet werden.
1. Eingabe Proben-ID
2. Abfrage anhand Proben-ID ob DCC gesetzt wurde
3. Erheben der anderen Daten

Ist unklar ob das die Woche noch möglich ist.
Gruß, Gordon

**Comment by BrittaTSI** [comment]
Das wäre meine Wunschimplementierung. Wenn das diese Woche noch ginge, wäre das super.
Als Fallback müßten wir die Eingabefelder / DropDown-Listen (erstmal) so markieren, daß ganz deutlich ist, welche Felder im DCC-Fall befüllt werden müssen / dürfen.
Das würde ich dann gerne mal Heinz-Jörg Müller und Jens Mühlner vorstellen.

**Comment by janhoffmann** [comment]
@ggrund-tsi Ich möchte an der Stelle einen kleinen Punkt in die Runde werfen:
Es wäre schön, wenn es möglichst unkompliziert für die Personen in der Station bleibt. Gerade bei wackeliger Internetverbindung ist ein mehrstufiger Prozess (auch wenn es nur Api calls im Background sind) schon eine Fehlerursache mehr.

Ich vermute in sehr vielen Stationen werden ausschließlich DCC konforme Kits benutzt, hier entsteht dann für die Personen die häufig im Ehrenamt die Testung durchführen ein unnötiger Mehraufwand.

Ich verstehe den Grundgedanken bei der Idee hier, aber vielleicht sollte man das ganze als eine Art aktivierbares Feature sehen und nicht als künftige Standardvariante. Das würde in nicht kommerziellen Stationen sehr helfen.
