### ISSUE TITLE
Verification of Test-ID

### ISSUE THREAD

**Issue by flo-so** [corona-warn-app/cwa-quick-test-frontend#193]
The entered Test-ID (Testergebnis erfassen) should be checked if it is a valid ID from the BfArM-Liste.
A tool tip that shows the Name (from the list) could also be added for a manual verification.

**Comment by janhoffmann** [comment]
![image](https://user-images.githubusercontent.com/1494946/124764574-6541bd80-df35-11eb-9d39-e81cf4bf934e.png)

@flo-so This is how it looks in my interface, is it different for you?

**Comment by flo-so** [comment]
For me in the mobile Version, it looks live this, and IT accepts the wrong Test-ID
![Screenshot_20210707-192009_Firefox](https://user-images.githubusercontent.com/84222822/124802736-967fb500-df58-11eb-9e53-3fbb0b879a99.jpg)

Maybe this is just a test or mobile version issue

**Comment by ascheibal** [comment]
The TestID field has two functions:
- provide a quicksearch function to the underlying BfArM List
- provide freetext functionality for testkids that are currently not in the BfArM List, but are indeed eligible and chargeable.

Be aware that, whatever you type in as testkid id, will be printed to the pdf from that is generated with the test result.
