### ISSUE TITLE
Position der Checkbox DCC-Consent verändern

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-frontend#201]
Auf den Screens 

1. zur manuellen Datenerfassung und 
2. zur Prüfung der Daten aus dem per QR-Code eingescannten Schnelltestprofil 

gibt es jeweils eine Checkbox zum DCC ganz unten in der Maske. Klickt der/die Tester:in diese an, werden oben in der Maske die beiden zusätzlichen Felder für den Standardisierten Vornamen / Namen angezeigt. Das ist unintuitiv und stört den Eingabefluß, da der/die Tester:in nochmal nach oben in die Maske scrollen muß um die Daten nachzutragen. 
Die Checkbox soll daher weiter oben in der Maske eingefügt werden.

Aktueller Status 
<img width="449" alt="Screenshot 2021-07-23 081341" src="https://user-images.githubusercontent.com/65922025/126743988-adc31fc6-6891-4182-ad21-28ecf6780529.png">
<img width="430" alt="Screenshot 2021-07-23 081448" src="https://user-images.githubusercontent.com/65922025/126743994-582ee7c8-5e93-41bb-9b90-594362ef177a.png">

Zielbild für Screen Dateneingabe. Analog umzusetzen für Screen für Korrektur der Daten aus dem Schnelltestprofil:
Vor dem Klick - neue Position der Checkbox zwischen den Feldern Nachname und Geburtsdatum.
![DCC-Consent_1](https://user-images.githubusercontent.com/65922025/126754235-97db9c6d-2088-489a-83c8-e1bc21975950.png)
Nach dem Klick - Felder Standardisierter Vorname / Name werden unter der Checkbox angezeigt.
![DCC-Consent_2](https://user-images.githubusercontent.com/65922025/126754242-5e56a1fc-6ebf-4bd0-829f-05fd53187ea7.png)

**Comment by janhoffmann** [comment]
+1

The current placement and hidden boxes until the box is checked is not understood by users
