### ISSUE TITLE
clarify requirements regarding PCR tests in Testcenter

### ISSUE THREAD

**Issue by ggrund-tsi** [corona-warn-app/cwa-quick-test-frontend#265]
How to adjust Schnelltestportal to enable PCR tests in Testcenter.
- enable Testcenter in usermanagement?
- add PCR test indicator in record patient data?
- adjust record test results to describe used PCR test for DCC and non-DCC? Adjust result value range.
- adjust API to consume new values
- adjust backend integration
- adjust PDF

**Comment by pschilli62** [comment]
Fragestellungen zur PCR Integration

[GG_Integration PCR Test in das Portal.docx](https://github.com/corona-warn-app/cwa-quick-test-frontend/files/7658788/GG_Integration.PCR.Test.in.das.Portal.docx)

**Comment by joerg-oppermann-tsi** [comment]
Done
