### ISSUE TITLE
iOS: Schnelltest Link -> In Corona-Warn öffnen funktioniert nur in Safari

### ISSUE THREAD

**Issue by noopliez** [corona-warn-app/cwa-quick-test-frontend#271]
## Describe the bug

Nachdem man vom Schnelltest-Anbieter einen Link für das Ergebnis zugeschickt bekommt (in meinem Fall vom Bayerischen Roten Kreuz) und diesen öffnet, landet man auf einer Seite, wo es die Möglichkeit gibt, den Link in der Corona-Warn-App zu öffnen. 

Auf der entsprechenden Seite steht beschrieben, wie das funktionieren soll. Man soll lange auf den Link drücken und dann im geöffneten Auswahlmenü 'in Corona-Warn öffnen' anklicken.

Das funktioniert **nicht** mit folgenden Browsern: `Firefox`,`Brave`,`Chrome`.

Bisher funktioniert nur der hauseigene Browser `Safari`.

## Expected behaviour

Ich hätte erwartet, dass es auch mit anderen Browsern statt nur dem hauseigenen funktioniert

## Steps to reproduce the issue

1. Auf Link von Schnelltest-Anbieter klicken (mit einem Browser der **nicht** Safari ist)
2. Lange auf den 'Schnelltest Link' drücken
3. Im Auswahlmenü nach 'in Corona-Warn öffnen' suchen
4. Nicht fündig werden

## Technical details

- Host Machine OS (Windows/Linux/Mac): 
  - iOS 15.1 iPhone 6S
  - Safari 15
  - Brave 1.32.3
  - Chrome 90.0.4664.101
  - Firefox Daylight 40.1

Screenshots Landing Page:

**Landing Page Brave** | **Landing Page Safari**
:-------------------:|:--------------------:
![Landing Page Brave](https://user-images.githubusercontent.com/71688793/146639818-4436c563-748a-4563-a025-45fe5ccfef5b.PNG) | ![Landing Page Safari](https://user-images.githubusercontent.com/71688793/146639877-e74e65ab-e8eb-48a5-963c-057e944030d0.PNG)

---

Screenshots Auswahlmenü:

**Brave** |  **Chrome**
:---------:|:------------:
![brave-options](https://user-images.githubusercontent.com/71688793/146640194-d227b8a5-15f7-4977-a995-42f3f5699514.PNG) | ![chrome-options](https://user-images.githubusercontent.com/71688793/146640197-1d681ea0-be54-4cc0-8e8f-a8b82b756287.PNG)
**Firefox** | **Safari**
![firefox-options](https://user-images.githubusercontent.com/71688793/146640286-8edeb1ea-eebe-468e-9254-ce0bfbe75b8a.PNG) | ![safari-options](https://user-images.githubusercontent.com/71688793/146640288-4092efe5-239f-4873-844e-bcabf45b6173.jpeg)

## Possible Fix

**Minimum**: Es sollte auf der Seite darauf aufmerksam gemacht werden, dass diese Funktionalität nur in `Safari` funktioniert. Ich habe sehr lange immer nur stumpf auf den Link geklickt, bis ich mal auf die Idee kam diesen Browser zu probieren 😁 .

**Nice to have**: Auch andere Browser bieten die Möglichkeit, den Link in der Corona-Warn zu öffnen.

**Comment by Ein-Tim** [comment]
Closely related to https://github.com/corona-warn-app/cwa-event-landingpage/issues/23

**Comment by kerstin-oppermann-tsi** [comment]
As @Ein-Tim mentioned this issue is related to issue in cwa-landing-page. It is not a problem that can be solved here in the quicktest repo. @noopliez Please refer your request here https://github.com/corona-warn-app/cwa-event-landingpage/issues/23
