### ISSUE TITLE
Email check wrong 

### ISSUE THREAD

**Issue by GeroellSuess** [corona-warn-app/cwa-quick-test-frontend#281]
Had the first customer, that had an + in his email address: test+bla@example.com

quick Test Profile in app accepts the + (tried it at home), but the frontend does not.

i cannot reproduce the error, because I cannot make screenshots at work. And I don’t have an access to a demo at home ;)

see rfc 5322

**Comment by janhoffmann** [comment]
I can confirm this error. My patient was used to filter incoming emails by a suffix.

**Comment by kerstin-oppermann-tsi** [comment]
This is a duplicate of this issue that we fixed just now. https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/288
Fix will be deployed within next days.

**Comment by Ein-Tim** [comment]
Same as https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/288.
