### ISSUE TITLE
Funktion zum Download der im Schnelltestportal erfaßten Testdaten durch Partner

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-frontend#300]
Problemstellung:
Nach Beendigung des Vertrags (nach Kündigung durch den Partner oder TSI) müssen wir ihm dem Partner die von ihm erhobenen und im Schnelltestportal gespeicherten Testdaten übergeben / bereitstellen. 
Diese Daten muß der Partner dann 10 Jahre vorhalten um den rechtlichen Anforderungen zur Aufbewahrung von Gesundheitsdaten zu genügen. 
Um diese Anforderung umzusetzen, bekommt der Partner die Möglichkeit, die von ihm erfaßten Testdaten herunterzuladen. 
Mit der Bereitstellung der Daten und der fristgerechten Löschung in unseren Systemen haben wir unsere Verpflichtungen gegenüber dem Partner erfüllt.
 
Vorschlag Dev zur Umsetzung: Konsolidierter Download aller Daten nach Beendigung des Vertrags. Keine Zwischendownloads während der Laufzeit. 
**To be discussed** - ist ein Download in mehreren Etappen / Pakete nicht günstiger? Siehe Betriebsthemen und Vorschlag von Martin Mitev weiter unten.

Task für Laborstream: Kommunikationsmaßnahmen, durch die der Partner zum Download aufgefordert und / oder auf den Ablauf der Frist hingewiesen wird.
Siehe auch Diskussion hier:
https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/300#issuecomment-1111988943
https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/300#issuecomment-1112050238

*****
**Operations hat Bedenken, daß wir eine zu hohe Last auf unseren Systemen erzeugen, wenn**

- sehr viele Partner
- zur gleichen Zeit
- alle in ihrem Mandanten angefallenen Daten

herunterladen. (Was ein sehr realistisches Szenario ist, wenn wir irgendwann zum Laufzeitende allen Partnern gleichzeitig kündigen.)
TBD - wie können wir das vermeiden / den Download entzerren?
Ideen:

- zeitlich versetzter Zugriff der Partner (tbd - wie genau könnten wir Partner dazu bringen, zeitlich gestaffelt auf die Funktion zuzugreifen?)
- in mehreren Paketen (nach Monaten oder Quartalen aufgeteilt)
- weitere...?
(siehe auch https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/300#issuecomment-1109506318)

*****

Die Vorgehensweise (bei konsolidiertem einmaligem Download zum Vertragsende) wäre dann folgende: 

- Kündigung zum Stichtag dd.mm.yyyy durch Partner oder TSI. Wir speichern das Kündigungsdatum im Backend.
- Bis zum Tag vor dem Datum, an dem die Kündigung wirksam wird, kann der Partner wie gewohnt Testdaten erfassen.
- Am Stichtag passiert im Schnelltestportal folgendes:
   - Wir deaktivieren die Funktion zur Erfassung weiterer Tests.
   - Wir kopieren alle noch im Kurzzeitarchiv (KZA) befindlichen Daten ins Langzeitarchiv (LZA). 
   Die Daten bleiben im KZA gespeichert um einen nachträglichen Zugriff zu ermöglichen. Jeweils nach Ablauf von 14 Tagen werden diese Daten (die dann normalerweise ins LZA übertragen werden würden) gelöscht (weil wir sie ja bereits ins LZA übertragen haben).
   - Wir aktivieren die Downloadfunktion, der Partner hat 4 Wochen Zeit, die Daten herunterzuladen.
- 4 Wochen nach dem Stichtag dürfen wir den Portalzugang des Partners deaktivieren und die Daten löschen
-> Vorschlag Norbert Völgyi zur effizienten Löschung: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/300#issuecomment-1109506318
To be discussed - wollen wir dem Partner doch die Möglichkeit geben, Daten während der Laufzeit herunterzuladen?

**Annahmen und Anforderungen übergreifend:**   
- Ausschließlich der vom Partner benannte Admin darf die Funktion nutzen können, keine andere Rolle.
- Der Admin darf nur die Daten herunterladen, die in seinem Mandanten erfaßt wurden.
- Erfolgreicher Login als Admin mit 2FA am Schnelltestportal gilt als hinreichende Autorisierung zum Download der Daten.
- Einfachste Variante - Beim Download werden jeweils alle Daten bereitgestellt, die bis zum aktuellen Zeitpunkt im Mandanten gespeichert wurden. (Keine Auswahl eines Berichtszeitraums, keine Inkremente.) 
- Alternative: Die Dateien können nur paketweise (für Monate oder Quartale) heruntergeladen werden 
- Der Export erfolgt on demand getriggered durch die Aktion des Admins, es werden keine Daten zum Export paketiert/vorbereitet. 
- Es werden nur die Daten heruntergeladen, keine Testbelege im PDF-Format.
- **Geklärt mit Legal: Wir erstellen ein CSV (oder mehrere) mit den Daten.** 
- Die Datei(en) wird/werden gezippt.
- Über die zum Download bereitgestellte ZIP-Datei wird ein Hashwert erzeugt. Dieser wird mit einem Zeitstempel und der Kennung des Partners in dem System (Imagemaster?!) abgelegt, wo auch die Partnerverträge langzeitgespeichert werden). Dies kann z.B. gemeinsam mit dem Vertrag des betreffenden Partners oder in einem separaten Dokument über alle Partner erfolgen. Die Werte Hashwert / Zeitstempel / Partnerkennung werden mindestens drei Jahre aufbewahrt.
**- Rückmeldung Laborstream - eine Verschlüsselung der heruntergeladenen Dateien wird nicht gefordert.**
- Vier Wochen nach Eintritt der Kündigung können die Daten aus dem Langzeitarchiv gelöscht werden. Hier 

**Anforderungen Frontend:**   

**Startseite:**
- Dem Admin wird auf der Startseite ein neuer Menüpunkt "Datendownload" (Wording tbd) angezeigt.
- Wurde der Vertrag gekündigt, wird außerdem ein Hinweistext in Infobox angezeigt "Bitte laden Sie unbedingt Ihre Daten herunter..." (Wording tbd).
- Klick auf Button führt auf Unterseite "Datendownload"

**Unterseite "Datendownload"**
- Auf der Unterseite "Datendownload" wird ein Download-Button angezeigt, dazu ein Erklärtext (was wird heruntergeladen, in welchem Format, was soll der Partner dann mit den Daten tun,... - Wording tbd). 
- Gegebenenfalls kann/muß der Admin einen Zeitraum auswählen, für den die Daten heruntergeladen werden sollen.
- Klick auf den Button startet den Download. Die Dateien werden über eine HTTPS-Verbindung bereitgestellt, sind also mindestens beim Transport verschlüsselt.
- Nach Abschluß des Downloads wird dem Admin eine Rückmeldung angezeigt, ob der Download erfolgreich war oder nicht. Außerdem Hinweis: "Bitte überprüfen Sie die heruntergeladenen Daten auf Korrektheit und melden Sie sich gegebenenfalls unter *Technische Hotline*, wenn es ein Problem gibt."
- _Falls_ wir Zwischendownloads zulassen wollen: Außerdem Hinweis "wenn in Ihren Teststellen aktuell noch weiterhin Tests durchgeführt werden, müssen Sie die Daten nach Abschluß aller Testtätigkeiten zum Vertragsende nochmals herunterladen um die Vollständigkeit zu gewährleisten". (Wording tbd)

**Nach dem Download:**
Wir:
- Speicherung von Hash der ZIP-Datei, Zeitstempel, Kunden-ID (s.o.) im Vertrags-Archivsystem
- Logging, ob (erfolgreicher) Download stattgefunden hat, mit Datum/Uhrzeit der Downloadversuche
- Löschen der Daten nach Ablauf der 4-Wochen-Frist

Partner:
- Partner muß nach Download prüfen, ob Datei formal ok ist (Vollständigkeit läßt sich schwer überprüfen) 
- Sollte der Partner Fehler finden (z.B. Datei korrupt, Daten offensichtlich unvollständig), so muß er sich an die Hotline wenden. 
Offener Punkt - wie gehen wir mit Partnern um, bei denen Download dauerhaft fehlschlägt? -> Klären mit Legal

**Comment by BrittaTSI** [comment]
Vorschlag Felix: 
Kündigungsdatum in Tabelle halten, dann alle Daten ins Langzeitarchiv, danach erst Download anbieten. 
- Klären mit Laborstream, daß dann keine Zwischendownloads notwendig sind. 
- Nach dem Datum, zu dem die Kündigung in Kraft tritt darf keine Erfassung von Testdaten mehr möglich sein.

**Comment by novoelgy** [comment]
Macht es nicht sinn die Downloadpackete auf Quartal / Monate auf zu teilen damit die auf einmal zu ertellende ZIP Datei nicht zu viel Zeit und Ressourcen dauert bei Partnern die 180K - 200K an tests haben ? 
--> wenn eine Aufteilung möglich is könnten die Partner schon jetzt aufgefordert werden alle Test-resultate für 2021 schon vorher herunter zu laden. Ds gibt die möglichkeit die Partner daruaf vor zu bereiten usw...

Da  wir nicht von Portal aus sagen können das der Partner die Datei wirklich heruntergeladen hat wird es keine 100% Information geben das der Download erfolgreiche war außer wenn wir das in einem Feld im Portal machen. Hat dann den Nachteil für die Partner die das nciht machen, wir keinen Nachweis haben.

Löschen würde ich nur bei abshcaltung des Services für alle auf einmal. Bei so einer großen Tabelle dauert eine Löschung Daten sehr lange und wird eventuel den DB cluster an die Limits treiben....(es ist nur 1 der Nodes read / write die anderen sind nur read) Mögliche Lösung den Langzeit DB Cluster aktiv zu nutzen und die Architabelle dahin zu migrieren, dann wird die Performenace vom Portal (wo noch Tests eingestellt werden ) nicht darunter leiden.

**Comment by VolBoeck** [comment]
Um den Download zu steuern, könnte man ja auch die Daten per Mail zusenden. Der Partner startet den Download und wir verschicken innerhalb von 24h die Daten per Mail?!?!

**Comment by BrittaTSI** [comment]
> Um den Download zu steuern, könnte man ja auch die Daten per Mail zusenden. Der Partner startet den Download und wir verschicken innerhalb von 24h die Daten per Mail?!?!

Das hatte ich auch zwischenzeitlich vorgeschlagen. Allerdings wurde der Vorschlag abgelehnt mit dem Hinweis, daß bei einer solchen Push-Lösung wir als Betreiber dafür verantwortlich wären, sicherzustellen, daß die Daten auch beim Partner ankommen. Und da kann ja einiges schiefgehen - eMail-Adresse nicht korrekt, Inbox voll,... was wir dann für mehrere tausend Partner aktiv monitoren müßten.
Vertraglich sind wir nur verpflichtet, die Daten zur Abholung bereitzustellen. Bei der hier vorgeschlagenen Pull-Variante ist der Partner dafür zuständig, die Daten herunterzuladen und muß sich aktiv bei uns melden, wenn es dabei zu Schwierigkeiten kommt.

**Comment by BrittaTSI** [comment]
> Macht es nicht sinn die Downloadpackete auf Quartal / Monate auf zu teilen damit die auf einmal zu ertellende ZIP Datei nicht zu viel Zeit und Ressourcen dauert bei Partnern die 180K - 200K an tests haben ? --> wenn eine Aufteilung möglich is könnten die Partner schon jetzt aufgefordert werden alle Test-resultate für 2021 schon vorher herunter zu laden. Ds gibt die möglichkeit die Partner daruaf vor zu bereiten usw...
> 
> Da wir nicht von Portal aus sagen können das der Partner die Datei wirklich heruntergeladen hat wird es keine 100% Information geben das der Download erfolgreiche war außer wenn wir das in einem Feld im Portal machen. Hat dann den Nachteil für die Partner die das nciht machen, wir keinen Nachweis haben.
> 
> Löschen würde ich nur bei abshcaltung des Services für alle auf einmal. Bei so einer großen Tabelle dauert eine Löschung Daten sehr lange und wird eventuel den DB cluster an die Limits treiben....(es ist nur 1 der Nodes read / write die anderen sind nur read) Mögliche Lösung den Langzeit DB Cluster aktiv zu nutzen und die Architabelle dahin zu migrieren, dann wird die Performenace vom Portal (wo noch Tests eingestellt werden ) nicht darunter leiden.

Aussage Martin - pro Download werden nicht mehr als 1 MB Daten anfallen, wenn der Partner alle Daten gleichzeitig herunterlädt. Anzahl der möglichen parallelen Streams sollte beschränkt werden. (Z.B. ein Download pro vCore pro Zeitpunkt) Monitoring, ob die Last doch zu hoch wird, dann notfalls Maschinen zuschalten. Bottleneck wird aber höchstwahrscheinlich in der DB liegen. 
Wir zippen mit ZIP-Stream. 
Martin / Julius schreiben das in der kommenden Woche im Detail auf.
Z.B. Persistent View mit Vorsortierung der Daten (Clusterung auf Partner). 
Nach Beendigung des Streams (ohne Fehler / I/O Exception) Dokumentation von technisch erfolgreichem Download, sonst Dokumentation von Fehler. (Funktion von TCP ermöglicht Monitoring, ob Stream erfolgreich war.)
Offene Punkte: Wie gehen wir mit Fehlern beim Download um?

**Comment by BrittaTSI** [comment]
Offener Punkt: 
- Wie informieren wir die Partner - automatisierte oder manuelle eMail, Signatur (von Wilfried?)
- Optimalerweise eine einheitliche eMail an alle. Ggf. Erinnerung nur an Partner, die noch nicht heruntergeladen haben.
- Outlook-Serien-eMail?
- Zeitversetzter / verzögerter eMail-Versand?

**Comment by VolBoeck** [comment]
Als Diskussionsgrundlage, hier die PRO/CONs für die einzelnen Möglichkeiten: 
Kündigungsdatum in SNow eintragen und autom. Mail aus SNow:
+ individueller Text
- Antworten kommen in SNow nicht gesichert an
- Fehler Versand wird von SNow nicht erkannt
Mail mit Partner in BCC:
+ Fehler Versand wird in der FMB erkannt
+ schneller Versand (500 Partner pro Mail)
- keine individuelle Ansprache (z.B. Partner ID)
- Antwort teilweise schwierig zuzuordnen
Serien-Mail:
+ individuelle Mail
- jeder Mailversand muss mit Enter bestätigt werden (FMB)

Signatur:
aktuelle Kommunikation aus der FMB signieren wir mit:
Mit freundlichen Grüßen
Ihr Telekom Onboarding-Service für Schnelltestzentren/Labore

**Comment by BrittaTSI** [comment]
> Als Diskussionsgrundlage, hier die PRO/CONs für die einzelnen Möglichkeiten: Kündigungsdatum in SNow eintragen und autom. Mail aus SNow: [+] individueller Text [-] Antworten kommen in SNow nicht gesichert an [-] Fehler Versand wird von SNow nicht erkannt Mail mit Partner in BCC: [+] Fehler Versand wird in der FMB erkannt [+] schneller Versand (500 Partner pro Mail) [-] keine individuelle Ansprache (z.B. Partner ID) [-] Antwort teilweise schwierig zuzuordnen Serien-Mail: [+] individuelle Mail [-] jeder Mailversand muss mit Enter bestätigt werden (FMB)
> 
> Signatur: aktuelle Kommunikation aus der FMB signieren wir mit: Mit freundlichen Grüßen Ihr Telekom Onboarding-Service für Schnelltestzentren/Labore

Automatisierung müßte in SNow implementiert werden, dann könnten wir große Anzahlen von personalisierten eMails versenden.
