### ISSUE TITLE
Provide a description for this repository

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quick-test-frontend#35]
## Current Implementation

The repository https://github.com/corona-warn-app/cwa-quick-test-frontend currently doesn't have description and the [README.md](https://github.com/corona-warn-app/cwa-quick-test-frontend/blob/master/README.md) is very general and doesn't explain what this repo is doing.
Even worse, the README.md says:

> This repository contains the **log upload** for the Corona-Warn-App.

## Suggested Enhancement

Remove the sentence "This repository contains the **log upload** for the Corona-Warn-App.", add a new one which explains the use of this repository and add a description. 

## Expected Benefits

Everyone understanding better what this repository is doing.

**Comment by ascheibal** [comment]
Hi, @Ein-Tim. Thanks for pinning that. We will correct this asap to avoid further confusing.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6382](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6382)

**Comment by Ein-Tim** [comment]
@ascheibal Any updates here? I just need a really short text for the overview of the repositories in the documentation repository. 

That would be nice! Thanks!

**Comment by Ein-Tim** [comment]
An answer has been given in https://github.com/corona-warn-app/cwa-quick-test-backend/issues/14.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks !
