### ISSUE TITLE
feat: QR-Code semantic

### ISSUE THREAD

**Issue by ascheibal** [corona-warn-app/cwa-quick-test-frontend#46]
## Feature description
QR Code shall contain an URI in the following form

**https://s.coronwarn.app?v=1#[base64-urlencoded JSON-Object]**
Attributes of JSON-Object:
```json {
"fn": "Vorname",
"ln": "Nachname",
"dob": "1990-01-01",   - >day of birth
"guid": "<sha256 hash of fn+ln+dob>",
"timestamp": 12345678 (Unix timestamp)
}
```
## Problem and motivation
QRCode shall be readable with new feature of Coronawarn.app

**Comment by a-trzewik** [comment]
Wie soll das QR-Code aussehen, das gescannt werden muss. (Button QR-Scan Erfassen)
In dem Code (den man scant) müssten Patienten Daten sein. Der code den man erzeugt hat nur Hautpdaten.
Jetzt läuft es auseinander. Man kann nicht den code scannen, der die Anwendung erzeugt hat, da da keine Patientendaten drin sind.

**Comment by ascheibal** [comment]
updated issue documentation:  
- urlencoding necessary
- guid contains sha-256 hash

**Comment by mlenkeit** [comment]
Does `guid` now change its attribute name to `hash`?
