### ISSUE TITLE
Question: Process description or flow chart?

### ISSUE THREAD

**Issue by raceface2nd** [corona-warn-app/cwa-quick-test-frontend#51]
Question

Hi,

we developed a web based platform for managing quick test results and patient data data while testing campaigns in companies.

We love that we see that the submission of quick test results to the CWA is in make.

To be able to provide this additional benefit feature to our company customers I am very interested on getting information on how the technical process is planned to deliver the test results to the CWA.

Are there any documents (sketches, descriptions, charts or whatever) you can provide that we might be able to prepare the ability on our technical side?

Can you also estimate when this feature will be available? We have some festivals and concerts which will be held somehow in the next months hopefully as demonstrator events in conjunction with quick testing. The event organizers would love to use the CWA as trusted instance instead of using different apps for ticketing, test results and pooled contact tracing. The first event which will take place is the "Bundesgartenschau" which is held every 2 years and which open doors in about 2 weeks. We would like to support the organizers of the Bundesgartenschau in making the event as save as possible by using CWA together with quick tests.

Sorry for that much text and thank you in advance!

Andy

**Comment by raceface2nd** [comment]
Thank you for handling my question that quick. I read in the issue tracker that someone mentioned a document from bioscitec which has been developed whithin a project for maximized efficiency in mass testing at events/ concerts.

Bioscitec and us are partner in this specific project which has started 6 months ago. We worked intensively on rapidisation of the testing itself especially in conjunction with apps (our project partner is [pass4all](https://www.pass4all.de/).

We also developed concepts how a nationwide network can work efficient with minimiced personal data use. In our oppinion there is a strong request by the population to capture personal data only in case of a positive test. We strongly believe that there is absolutely no necessity to capture personal data in the test center except in positive cases. Even then the user can provide these data directly through the app without having them routed through the testcenter.

This will be very important for the acceptance of the whole process including the event registration by the people.

Our system which is developped especially for test campaigns in companies consists of 4 components which strongly separate personal data and test data in different databases and different backend-api's. We can simplify the personal data down to the employee ID which should be unique in every company. This is the only value which is stored together with the test result.

If there is any interest in more information about our work please feel free to PN.

Please consider as well that the Bfarm-ID of the test should delivered by the test center. In our work and system each test is individualized by qr codes defined by us, which contain the Bfarm-ID and an individual serial. Until now the interest in what test has been used was nearly 0 but increasing. The company and the tested employee receive the Bfarm ID of the used test as well as the unique serial together with the test result. We recognized an increasing interest to the test by the tested people. With this the bfarm ID together with the result the people get the option to get more information about the indivual test kit if they want.

**Comment by Ein-Tim** [comment]
*Disclaimer: I'm neither a community manager nor a developer.*

Hey @raceface2nd 👋

Very interesting questions and also a very interesting solution you found. 
I'm not quite sure wether your issue's in the right place here, for proposals (your second comment seems like a proposal) we use the https://github.com/corona-warn-app/cwa-wishlist repository. 
The question you asked in the initial post may also be petter placed in the https://github.com/corona-warn-app/cwa-documentation repository.

@dsarkar Could you take a look at this?

**Comment by dsarkar** [comment]
Hi @Ein-Tim Thanks for pinging me!

Hi @raceface2nd, Thanks for posting contributing here. Could you, do as suggested by @Ein-Tim:
Create separate issue in  the https://github.com/corona-warn-app/cwa-wishlist repository for feature requests/enhancements,and the question in the https://github.com/corona-warn-app/cwa-documentation repository, respectively. We will try to deal with all the issue from there then.

Many thanks!

**Comment by raceface2nd** [comment]
@Ein-Tim @dsarkar I am happy that you guys are open to such ideas and love to support. According to your suggestion I will raise a topic in the wishlist repository.

I already dropped a comment on a comment with an early concept from bioscitec. This concept has developed over the past months together with bioscitec and other partners.

Please feel free to contact me if you are interested in an exchange about our work and experiences in the project group.

https://github.com/corona-warn-app/cwa-wishlist/issues/371#issuecomment-817224452

**Comment by raceface2nd** [comment]
@Ein-Tim may you point out the specific part in my second comment you'd like to see in the wishlist? Don't wont to bother all audience with everything. Or should I simply reference to the comment when I add the issue?

**Comment by Ein-Tim** [comment]
@raceface2nd 

I think your second comment is an enhancement, or? These are normally handled in the wishlist, since it applies to the backend as well as to iOS and Android.

Also I think that we're on the way to mix up two topics, first the question on documentation (OP of this issue), which should be placed in the documentation repository & the enhancement request in the second comment.

You don't bother anyone there, these repos are there for the communities issues. From there on, one of the community managers (@dsarkar) will pick up your issue, mirror it into the internal ticket system and the developers will look into it.

**Comment by raceface2nd** [comment]
Correct, the second comment contains enhancement suggestions as well. I am not sure which paragraph exactly woke your interest as I spoke about several topics.

Is it the part of waiting with handling personal data until a positive test result has been provided by the test center or the part in providing the Bfarm ID together with the test result?

**Comment by Ein-Tim** [comment]
It was the part of only handling personal data if the test result is positive. 

I want to thank you for participating here with your knowledge! This is really nice because you have the insights and ideas what would be possible! Thanks! Have a nice evening!

**Comment by raceface2nd** [comment]
@Ein-Tim there is no reason to thank. I am glad that the authorities late but finally decided to make more of the app as an expensive PCR test submission system. It's also kind of selfish somehow to support the intended optimizations to hopefully get all of our colleagues back to work somehow this year.

Btw I added a new enhancement issue to the wishlist repo. It's much more text due to more detailed descriptions. 

https://github.com/corona-warn-app/cwa-wishlist/issues/446#issue-855475498

**Comment by Ein-Tim** [comment]
@raceface2nd 

Thanks for the very detailed issue in the wishlist! 
One of the community members will pick it up soon. 

Have a nice day!

**Comment by raceface2nd** [comment]
@dsarkar agree.

**Comment by Ein-Tim** [comment]
@raceface2nd 

Could you close this issue here since we moved to https://github.com/corona-warn-app/cwa-wishlist/issues/449 & https://github.com/corona-warn-app/cwa-wishlist/issues/446? 

I think @dsarkar can't close issues here, so easiest would be if you close it! 

Thanks again for sharing your ideas! The last [comment](https://github.com/corona-warn-app/cwa-wishlist/issues/446#issuecomment-818980219) in https://github.com/corona-warn-app/cwa-wishlist/issues/446 was really interesting to read for me!

**Comment by raceface2nd** [comment]
@Ein-Tim glad that one finds it interesting.

Will close this thread. You're right.
